selenoid:
  host: localhost
  port: 4444
  version: 89.0
  enableVNC: true
  enableVideo: true
  videoFile: ${project.name}_${browser}_${selenoid.version}
  videoFormat: .mp4
  enableLog: true
  logFile: ${project.name}_${browser}_${selenoid.version}
  logFormat: .log